# Generated by Django 6.0.6 on 2026-07-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldcupapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
